### ISSUE TITLE
Install stable keda in SiDi k8s cluster.

### ISSUE THREAD

**Issue by robsondepaula** [sidilabs/keda#5]

**Comment by JonasMatos0** [comment]
keda have beem properly placed under SiDiś kubernetes cluster.

NAME                                      READY   STATUS    RESTARTS   AGE
keda-metrics-apiserver-6464d8dfb9-dxf8q   1/1     Running   0          5m5s
keda-operator-7776cfd966-wvj5d            1/1     Running   0          5m5s
